### ISSUE TITLE
MCEdit (1068 & 1066) crash on startup

### ISSUE THREAD

**Issue by FireRainV** [mcedit/mcedit2#238]
MCEdit Version: 2.0.0alpha-1068 | Operating system: Windows 10 Pro 64-bit

At the moment I opened the MCEdit on versions 1066 and 1068, the MCEdit crashed with the next error:

-----------------------------------------------------------------------------------------
[INFO][main.py:173]:MCEdit2 version 2.0.0alpha-1068 starting...
[INFO][acceleratesupport.py:13]:OpenGL_accelerate module loaded
[INFO][arraydatatype.py:275]:Using accelerated ArrayDatatype
[ERROR][main.py:195]:Unhandled Exception: 
	'ModelPlayer' object has no attribute 'modelTexture'
Traceback (most recent call last):
  File "mcedit2\main.py", line 218, in <module>  
  File "mcedit2\main.py", line 214, in main  
  File "mcedit2\util\profiler.py", line 73, in _wrapper (self is a Profiler)
  File "mcedit2\main.py", line 184, in startup  
  File "c:\users\rio\documents\mcedit2-distrib\buildbot\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module (self is a FrozenImporter)
  File "mcedit2\editorapp.py", line 14, in <module>  
  File "c:\users\rio\documents\mcedit2-distrib\buildbot\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module (self is a FrozenImporter)
  File "mcedit2\plugins\__init__.py", line 13, in <module>  
  File "c:\users\rio\documents\mcedit2-distrib\buildbot\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module (self is a FrozenImporter)
  File "mcedit2\editortools\generate.py", line 17, in <module>  
  File "c:\users\rio\documents\mcedit2-distrib\buildbot\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module (self is a FrozenImporter)
  File "mcedit2\rendering\worldscene.py", line 13, in <module>  
  File "c:\users\rio\documents\mcedit2-distrib\buildbot\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module (self is a FrozenImporter)
  File "mcedit2\rendering\chunkupdate.py", line 12, in <module>  
  File "c:\users\rio\documents\mcedit2-distrib\buildbot\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module (self is a FrozenImporter)
  File "mcedit2\rendering\chunkmeshes\entitymesh.py", line 15, in <module>  
  File "c:\users\rio\documents\mcedit2-distrib\buildbot\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module (self is a FrozenImporter)
  File "mcedit2\rendering\chunkmeshes\entity\models.py", line 172, in <module>  
  File "mcedit2\rendering\chunkmeshes\entity\models.py", line 153, in addModel  
  File "mcedit2\rendering\chunkmeshes\entity\models.py", line 142, in cookEntityModel  
AttributeError: 'ModelPlayer' object has no attribute 'modelTexture'
-------------------------------------------------------------------------------------

The MCEdit didn't crashed to me on "MCEdit 2.0.0alpha-1050",
I think its because of my Operating system or something is wrong with the new Render player model.

I will wait for comments, thanks.

**Comment by codewarrior0** [comment]
Fixed

**Comment by FireRainV** [comment]
Thanks, its now work in the 2.0.0alpha-1071
